stages:
- name: build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: ' mvn clean package'
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test001:${CICD_EXECUTION_SEQUENCE}
      pushRemote: false
      registry: harbor.mihoyo.com
    env:
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60000
notification: {}
